### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Filoppi** [EndlesslyFlowering/Starfield-Luma#8]
Mandatory for 1.0 release:
- [x] Take HDR screenshots and fill mods page (+donations links)
- [x] Finalize HDR tonemapper
- [x] Normalized LUTs 2.0+
- [x] Hook up custom shader params (and related custom menu settings)
- [x] Fix custom menu settings value disappearing after change
- [x] Enable HDR on screen when setting the HDR settings (don't disable it when setting back SDR)
- [x] Automatically determine peak HDR brightness from DX information
- [x] Fix some LUTs crushed blacks, broken colors around shadow and gamma correction
- [x] Greying out the HDR brightness sliders in SDR (and all related HDR settings)
- [x] Test everything (e.g. changing buffers, LUTs normalization applied to all LUTs, ...)
- [x] Allow BT.2020 colors to pass through (for increased saturation)
- [x] Fix sharpening creating shimmer in HDR (can't repro anymore)
- [x] Review Porima Palms passing through full black with FSR2? (can't repro, probably not a real problem, the code setup was wrong)

For 2.0 update:
- [ ] Fix Shader Injector crashing when changing resolution or window mode?
- [ ] Change DICE tonemapper to use y/luminance PQ (like Prey), no ICtCp
- [ ] Upgrade DX shader compiler to the last version
- [ ] LUTs extrapolation (Test or fix overdrive/time jump colors: https://streamable.com/tqg8vi
- [ ] Improve LUTs normalization (fix https://github.com/EndlesslyFlowering/Starfield-Luma/issues/26) (normalization also brings the average brightness down?)
- [ ] Change DICE to work in Luminance+PQ without ICtCp
- [ ] Shorten the HDR tonemapping path code (strict color grading)
- [ ] Default to strict color grading (and maybe remove the old path completely)? Also update to RenoDX new TM instead OpenDRT?
- [x] Fix DLSS TO FSR FG mod crashing on boot if display mode was set to 1 (or 2)
- [ ] Fix DLSS TO FSR FG mod having flickering on UI
- [x] Fix FSR3 FG UI not blending correctly in HDR. Also maybe it clips all HDR colors? We have multiple approaches here (1 - store every other post processing color buffer in sRGB gamma space so that the FSR UI blends in correctly, then linearize it at the end - DOES NOT WORK AS FSR3 UI DRAWS AFTER COPY) (2 - force the ScaleForm UI composition shader to run with FSR FG as well, but make it target the UI buffer itself so we can linearize it) (3 - replace the FSR FG shader with some new code hooks to FSR code) (4 - find the shader that applies the UI alpha intensity user setting and add gamma linearization to it) (5 - edit all the ScaleForm shaders to apply a brightness boost and linearize before output)
- [ ] Fix the remaining buffers that are not upgradable to FP16 (and AMD) (which also means they clip negative colors, and have banding (proven))
- [ ] Verify ship light travel engine fire burst being of the same color as vanilla
- [x] Change mid gray from 0.18 to an actually accurate value? (update: it's fine, we established through tests that 0.18 is good enough, and it's actually accurate)
- [x] Gamut mapping (in CIE 1931)
- [x] Fix photo mode screenshots
- [x] Development: Release the mod source code ~~and add the shader injector source~~ ([Injector source here](https://github.com/Nukem9/sf-shader-injector))
- [x] Support new SF patch
- [x] Double check CAS changes from new SF patch
- [x] Re-analyze sundisk/lensflare shader (Bethesda already fixed it anyway)
- [x] Remove tweaks to our lens flare/sun shader, and possibly completely remove the shader
- [x] Fix the latest bug reported by users where LUTs produce black pixels
- [x] FSR2 clips any color beyond BT.709 from the renderer, maybe CAS as well (it's probably actually that the renderer just doesn't spit out any non BT.709 color, so we can ignore this)
- [x] Fix remaining black dots/patches on UI (especially on loading screens?)
- [x] Fix black squares in the characte screen UI, next the rendering of the weapons (it's caused by CAS, not the UI) [example](https://forum.nexusmods.com/index.php?showtopic=13321137/#entry129507794)
- [x] Fix purple lines in the characte screen UI, next the rendering of the planet (it's caused by CAS?, we can't reproduce) [example](https://i.imgur.com/MsnN8TH.jpeg) (presumed fixed or a user side problem)
- [x] Fix black patches on highlights (maybe already fixed in 1.0.1) [example](https://forum.nexusmods.com/index.php?showtopic=13321137/#entry129517295)
- [x] Crash on exit? (Reported by SK's Kal) (fixed until proven otherwise)
- [x] Fix ReadMe.txt referencing old settings names
- [x] Fix PostProcessRestore() not restoring LUTs night vision colors as expected (fixed by LUTs extrapolation)
- [x] Specify that SDR is 10bit in ReadMe
- [x] Finish ACES/OpenDRT HDR
- [x] Detect DLSS FG and disable scRGB
- [x] Allow scRGB with DLSS 3 FG (for future updates that support it) through a config edit
- [x] Fix FSR3 FG compatibility (it engages but only shows duplicate frames?)
- [x] Remove HDR related settings that came with the new SF patch
- [x] Fix "Vanilla menu LUTs" checks to include all menus
- [x] Some people report that engaging HDR the way we do it breaks their "display" (https://twitter.com/Fluxic3/status/1728292770438394070 - Dell G15 5530, https://twitter.com/dharlequin/status/1725231401505587491) (presumed fixed or a user side problem)
- [x] Fix starting the game in scRGB HDR with DLSS FG and HDR10 with FSR FG

Extras, low priority and optional:
- [ ] Confirm Luma works with Intel iGPU and Intel Arc GPUs (at this point we can assume it's ok? We got no bug reports)
- [ ] Publish a simplified (lut only) version on the Creation store?
- [ ] Occasionally our HDR settings are added twice in the main menu? I can't reproduce it anymore but it happened
- [ ] Fix photo mode screenshots not working with FSR 3 FG
- [ ] Fix photo mode screenshots not including photo mode frames (users can select frames from the photo mode settings, but Luma uses a custom rendering path render screenshots and it forcefully skips the UI as the screenshots is captured just before the UI blends in)
- [ ] Investigate some ini configs (like "fSpaceGlowBackgroundScale" and "fStarIntensity") that people often change and come up suggested values that look good with Luma
- [ ] Gamut mapping in Oklab or Darktable UCS (more accurate)
- [ ] Add more fine tunable ways to boost saturation/vibrance on highlights (e.g. copy from Pumbo AdvancedAutoHDR)
- [ ] Make `Plugin\dist\deploy-release.ps1` clean up the data shaders folder and then call `compile_all_shaders.ps1` to always automatically recompile the latest shaders
- [x] Try doing sRGB<->2.2 gamma correction by luminance instead of by rgb channel (it makes little sense, but it's possible it looks good and conserves the sRGB original colors, only shifting their brightness; though it would make sense if they actually designed the LUTs on sRGB gamma screens, and just made them very low contrast on purpose)
- [x] Change the ScaleForm UI composition shader to that it can also read the background directly, as HDR would benefit from a custom blend model (it really looks fine anyway)
- [x] HDR10 support
- [x] #11
- [x] Polish film grain strength and settings
- [x] Improve and fix CAS
- [x] Fix bink video matrices (videos are BT.709 but where interpreted as BT.601, they are not HDR)
- [x] Development: Add setting to force HDR scRGB swapchain but tonemap to SDR
- [x] Improve AutoHDR on bink videos (make it optional)
- [x] Make sure HDR UI composition doesn't mess around with DLSS FG
- [ ] Try changing LUTs input mapping from sRGB to PQ (use the range from 0 to 203 nits, or 0 to 100 nits). This means changing the code that reads the 4 input LUTs of the LUT mixing shader and adding a bilinear sampler there to shift the input coords from sRGB to PQ. This could provide better quality on output as it would store LUTs with a more perceptually accurate encoding, which is especially good given we already correct/normalize LUTs a lot, so maintaining the original untouched sRGB source value isn't going to give us a quality boost.
- [ ] Add user gamma setting for SDR output case (`SDR_LINEAR_INTERMEDIARY`). By default the game is 2.2, but given we use FP16 buffers, we could afford to go sRGB or 2.4 or anything else.
- [ ] Fix toggling SDR/HDR crashing if done through the ReShade widget? This does not happen if FG is disabled. It happens once in a while when using DLSS FG, and all the times when using FSR FG. Changing `Display Mode` from the "official" Luma settings menu or from the ReShade widget within the pause menu doesn't crash the game; likely due to FG being disabled in menus (and possibly re-initialized when unpausing the game) (this means it's probably not a threading issue). For now we have hidden the display mode setting when FG is enabled
- [ ] Optimize shaders
- [ ] Delete all unused old code across shaders
- [ ] Add Pumbo's Film Grain
- [ ] Try AGX tonemapper?
- [ ] Increase mixed LUTs resolution for better results (we already have Tetrahedral Interpolation so it's not really needed)
- [ ] Find out what LUT is currently in use in c++ and tell shaders whether to do LUT correction or not (as an optimization, but also as a way to selectively decide which LUT correction adjustments to make)
- [x] Change HDR DICE tonemapper to work on a color space that better represents luminance compared to scRGB (this also has drawbacks)
- [x] Development: Fix shaders reload crashes? (fixed at the cost of memory leaks)
